<?php

define('ADVENT_02_REGEXP_MATCH_GROUP_CHARACTER', 3);
define('ADVENT_02_REGEXP_MATCH_GROUP_PASSWORD', 4);
define('ADVENT_02_REGEXP_MATCH_GROUP_LIMITS', 1);
define('ADVENT_02_REGEXP_MATCH_GROUP_POSITIONS', 1);